name: Release

on:
  push:
    branches:
      - main
      - ci/ttk-build-web-desktop

permissions:
  contents: read # for checkout

jobs:
  publish-tag-release:
    name: Release
    runs-on: self-hosted
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
    steps:
      - name: "@ - Checkout current repository"
        uses: actions/checkout@v4

      - name: "@ - Setup node"
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: 'pnpm'

      - name: "@ - Setup pnpm"
        uses: pnpm/action-setup@v4
        with:
          run_install: true

#      - name: "@ - Run release"
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        run: pnpm exec semantic-release

      - name: "@ - Install Rust stable"
        uses: dtolnay/rust-toolchain@stable

      - name: "@ - Install Rust cache"
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'
      - name: "@ - Run release"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: pnpm run tauri:build
